name: mobileappfrontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  signalr_netcore: ^1.3.7
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  fluttertoast: ^8.2.5
  url_launcher: ^6.2.6
  get_it: ^7.7.0
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"

# notes:
# 1. if you change this, please run again flutter pub run flutter_native_splash:create
# 2. do not use dark mode in phone, this doesn't work
# 3. raw splash images is in ImagesRaw folder
flutter_native_splash:
  color: "#01c5ff"
  color_dark: "#01c5ff"
  image: assets/splash_image.png
  image_dark: assets/splash_image.png
  android: true
  ios: false
  web: false

  android_12:
    color: "#01c5ff"
    color_dark: "#01c5ff"
    image: assets/splash_image.png
    image_dark: assets/splash_image.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
